@baseUrl = http://localhost:8080

# @name login
POST {{baseUrl}}/token/login
Content-Type: application/json

{
  "email": "marcos@example.com",
  "password": "123456"
}

@authToken = {{login.response.body.token}}

###

# @name findAll
GET {{baseUrl}}/users
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name findById
GET {{baseUrl}}/users/1
Authorization: Bearer {{authToken}}
Content-Type: application/json

###

# @name create
POST {{baseUrl}}/users/register
Content-Type: application/json

{
  "name": "admin",
  "email": "admin@example.com",
  "password": "123456",
  "phones": [
    {
      "number": "988776655",
      "type": "Celular"
    }
  ]
}

###

# @name update
PUT {{baseUrl}}/users/1
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "name": "Marcos Felipe Amorim",
  "email": "marcos@example.com",
  "password": "123456",
  "cpf": "11122233344",
  "phones": [
    {
      "number": "988776655",
      "type": "Celular"
    }
  ]
}

###

# @name delete
DELETE {{baseUrl}}users/1
Authorization: Bearer {{authToken}}
Content-Type: application/json