# docker-compose.yml
version: "3.8"
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: dbshop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
