@baseUrl = http://localhost:8080

# @name login
POST {{baseUrl}}/token/login
Content-Type: application/json

{
  "email": "marcos@example.com",
  "password": "123456"
}

@authToken = {{login.response.body.token}}

###

# @name findAll
GET {{baseUrl}}/orders
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name findById
GET {{baseUrl}}/orders/1
Authorization: Bearer {{authToken}}
Content-Type: application/json

###

# @name create
POST {{baseUrl}}/orders
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "totalPrice": 200.00,
  "discount": 10.00,
  "paymentMethod": "CREDIT_CARD",
  "status": "PENDING",
  "createdAt": "2024-12-17T14:00:00",
  "updatedAt": "2024-12-17T14:00:00",
  "accountId": 1,
  "deliveryAddressId": 1,
  "items": [
    {
      "product": {
        "id": 1,
        "name": "Celular",
        "description": "Descrição do celular",
        "price": 200.00
      },
      "quantity": 1
    },
    {
      "product": {
        "id": 1,
        "name": "Notebook",
        "description": "Descrição do notebook",
        "price": 2000.00
      },
      "quantity": 1
    }
  ]
}

###

# @name update
PUT {{baseUrl}}/users/3
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "name": "Marcos Felipe Amorim",
  "email": "teste@example.com",
  "password": "123456",
  "cpf": "11122233344",
  "phones": [
    {
      "number": "988776655",
      "type": "Celular"
    }
  ]
}

###

# @name delete
DELETE {{baseUrl}}/users/3
Authorization: Bearer {{authToken}}
Content-Type: application/json